version: 2.1

# Define the jobs we want to run for this project

jobs:
  build:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: echo "build project"
      - run: yarn
      - run: yarn build
  test:
    docker:
      - image: cimg/node:19.7.0
    steps:
      - checkout
      - run: echo "Running tests"
      - run: yarn
      - run:
          name: Run tests
          command: node --expose-gc ./node_modules/.bin/vitest

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
